project:
  name: jsoup
  repo_path: /data/henrique/multiagent_refactoring/data/repositories/commons-lang

runs: 2

target:
  smell: IM
  smell_name: Insufficient Modularization
  target_type: class
  target_name: org.apache.commons.lang3.reflect.TypeUtils

planner:
  base_config: /data/henrique/multiagent_refactoring/mvp/planner/config_im.yml

source_refactor:
  base_config: /data/henrique/multiagent_refactoring/mvp/source_refactor/config.yml

output:
  runs_dir: /data/henrique/multiagent_refactoring/data/runs